### PR TITLE
Added new line

### PR DESCRIPTION
**Pull request by Mahich123**
Please check my work . Added new line.

### CODE REVIEW

**Comment by AnirudhPanda** [comment]
Resolve merge conflicts!

**Comment by Mahich123** [comment]
i don't know why showing conflict can you simplify me this
??

**Comment by AnirudhPanda** [comment]
> i don't know why showing conflict can you simplify me this ??

https://www.simplilearn.com/tutorials/git-tutorial/merge-conflicts-in-git

**Comment by Mahich123** [comment]
@AnirudhPanda  resolved other one can you check it

**Comment by AnirudhPanda** [comment]
> @AnirudhPanda resolved other one can you check it

Still there are conflicts

**Pull request closed without merging**
