### PR TITLE
Add tests and GitHub Actions

### LINKED ISSUE #2: Add github actions

### LINKED ISSUE #10: [BUG] Improper implementation of the `randomInt()` function
# Bug Description
The `randomInt()` function implemented is not valid for this use case. The function is shown below:

Screenshot_20211001_034316

As per [W3Schools](https://www.w3schools.com/js/js_random.asp) this generates a random number between `min` and `max` (**BOTH INCLUDED**), which is causing the issue.

Since both `min` and `max` can be included, the code is crashing of index out of bounds error sometimes while testing, when the `randomInt()` returns `max`. A sample screenshot is given below:

Screenshot_20211001_034241

### PR DESCRIPTION
**Pull request by gitaalekhyapaul**
# Description
- Added tests using Jest
- Added GH Actions
- Fixed a bug in `randomInt()`

Fixes #10
Fixes #2

### CODE REVIEW

**Comment by AnirudhPanda** [comment]
I have changed the function name yesterday!
Can you check that once and propose changes accordingly

**Comment by gitaalekhyapaul** [comment]
@AnirudhPanda fixed the issue in https://github.com/Opentek-Org/bookquotes/pull/11/commits/bc3f715f7d9fdc70ebeb4b439a76816268bbe796

**Comment by AnirudhPanda** [comment]
Hey @gitaalekhyapaul 
we have a new function to be added with this #13 PR

You can check that PR too and can suggest anything.

I will see to this PR

**Comment by AnirudhPanda** [comment]
Can you please describe what the gh action does?

**Comment by gitaalekhyapaul** [comment]
Hey @AnirudhPanda , it seems that #13 follows the older method of testing. I would suggest merging this PR and then telling that contributor to re-base

**Comment by gitaalekhyapaul** [comment]
> Can you please describe what the gh action does?

The GH action installs dependencies and then runs the unit tests. I am using Jest to run the unit tests.

**Comment by saif-malik-01** [comment]
Hey @gitaalekhyapaul  ! Basically the main motive of PR #13 is to implement new functionality in the functions and update the readme accordingly. You can check and re implement the test according to the new code base.

**Comment by gitaalekhyapaul** [comment]
I have gone through the code @saif-malik-01 , but it follows an older method of testing, which cannot be automated through GH actions. The step to solving this issue is to merge this PR and then you can re-base to incorporate the new test framework in your code.

**Comment by saif-malik-01** [comment]
@gitaalekhyapaul you are right, is it ok if I don't implement any test and only make a PR with functionality changes.

**Comment by gitaalekhyapaul** [comment]
@saif-malik-01 why not wait for this PR to get merged? You can just refactor your code after that.

**Comment by gitaalekhyapaul** [comment]
Hey @AnirudhPanda , I guess we are ready to merge this PR, let me know if you have any other queries :+1:

**Comment by AnirudhPanda** [comment]
Great @gitaalekhyapaul  and @saif-malik-01 

Merging this PR but I want someone to update the Readme to what changes we have did with the package!
Will you do it @gitaalekhyapaul 

I will publish the new patch in 1-2 days

**Comment by gitaalekhyapaul** [comment]
Yeah sure, @AnirudhPanda ... anyways I have to work on the greetings workflow after this. I'll help you out for sure!

**Comment by AnirudhPanda** [comment]
> Yeah sure, @AnirudhPanda ... anyways I have to work on the greetings workflow after this. I'll help you out for sure!

Thanks man!
Appreciate it

**Pull request merged**
