### PR TITLE
Added new Quotes

### PR DESCRIPTION
**Pull request by DADDY-DOUBLESHOT**

### CODE REVIEW

**Comment by DADDY-DOUBLESHOT** [comment]
Added new quote @AnirudhPanda

**Comment by DADDY-DOUBLESHOT** [comment]
I have modified the Hashmap now we can search in O(1) to find the sent Quotes

**Comment by AnirudhPanda** [comment]
Hey @DADDY-DOUBLESHOT 
A quick suggestion

Create an issue for the same (using hashmap thing) and then create a PR only to solve that issue!
This will be helpful for us too and it is a good practice to do one thing at a time

**Comment by DADDY-DOUBLESHOT** [comment]
Thank you @AnirudhPanda  for mentioning those details about my PR . I will  create those issue and perform those tasks ASAP , PS this is my first PR thanks for your humble guidance :)

**Pull request closed without merging**
