### PR TITLE
Inspire quotes functionality and test added - #3

### PR DESCRIPTION
**Pull request by saif-malik-01**
* Implemented the functionality in getLines and getRandomLines to get specific type quotes #3.
* Test added for those functionality.
* Add type abbreviation in readme.

### CODE REVIEW

**Comment by AnirudhPanda** [comment]
Is everything good here? @saif-malik-01 

@gitaalekhyapaul do you have anything to say about these changes?

**Comment by saif-malik-01** [comment]
From my perception everything is ok.

**Comment by AnirudhPanda** [comment]
Great @saif-malik-01 

would you like to review #31

**Comment by gitaalekhyapaul** [comment]
image
@AnirudhPanda can you run this PR locally? It seems that the tests aren't running locally

**Comment by gitaalekhyapaul** [comment]
Also, @saif-malik-01 did you re-base after PR #11 got merged? I can see my code changes in your git blame.

The git blame seems very messy, you should re-base your branch with the upstream, and then add your code.

**Comment by saif-malik-01** [comment]
@gitaalekhyapaul I checked on my system all test are passed.

**Comment by gitaalekhyapaul** [comment]
> @gitaalekhyapaul I checked on my system all test are passed.

This might be because you did not re-base with upstream?

**Comment by saif-malik-01** [comment]
@gitaalekhyapaul ops! I forgot that , thanks.

**Pull request closed without merging**
