### PR TITLE
Inspire quotes functionality and test added - #3

### PR DESCRIPTION
**Pull request by saif-malik-01**
* Implemented the functionality in getLines and getRandomLine to get specific type of quotes #3 .
* Test added for those functionalities.
* Add type code abbreviation in readme.

### Tests
2021-10-03-105412_1366x768_scrot

### CODE REVIEW

**Comment by AnirudhPanda** [comment]
Looks good!!
How about you @gitaalekhyapaul

**Review by gitaalekhyapaul — APPROVED** [review]
LGTM :+1:

**Comment by AnirudhPanda** [comment]
After this merge, I should publish to npm asap!

Great work again @saif-malik-01 
Thanks for all the help @gitaalekhyapaul

**Comment by gitaalekhyapaul** [comment]
No problem, glad I could help!

**Pull request merged**
