### PR TITLE
Add quote to inspire.json file

### PR DESCRIPTION
**Pull request by dipankarmaharana**

### CODE REVIEW

**Comment by AnirudhPanda** [comment]
Create a new PR @dipankarmaharana

**Comment by AnirudhPanda** [comment]
@PrafulAnand the labeler didn't work here?

**Comment by PrafulAnand** [comment]
when was this PR opened ?

**Comment by AnirudhPanda** [comment]
> main branch and not v1.1.0

Yeah observed it!

**Pull request closed without merging**
