### PR TITLE
add a book-quote from The fault in our stars

### PR DESCRIPTION
**Pull request by aniketpathak028**
add a book quote from "The fault in our stars" by "John Green"

### CODE REVIEW

**Comment by aniketpathak028** [comment]
@AnirudhPanda pls review and approve my PR

**Comment by aniketpathak028** [comment]
@AnirudhPanda pls review and approve my PR

**Comment by AnirudhPanda** [comment]
Resolve merge conflicts!

**Comment by aniketpathak028** [comment]
@AnirudhPanda resolved this issue merge it pls

**Pull request merged**
