### PR TITLE
Add auto labeler 39 

### PR DESCRIPTION
**Pull request by PrafulAnand**
Issue -#39
These are the initial set of labels that I thought of we can add to the repo

@AnirudhPanda  Inputs required -:

How can I test this change?
Also do we require more labels to be added?

### CODE REVIEW

**Comment by PrafulAnand** [comment]
@AnirudhPanda take look at the closed pull request here https://github.com/PrafulAnand/bookquotes/pull/12
Was able to achieve the multiple labels too

**Comment by AnirudhPanda** [comment]
Great!
We just need `hacktoberfest` and `data` label

**Comment by PrafulAnand** [comment]
> Great! We just need `hacktoberfest` and `data` label

ok made the requird changes take a look

**Comment by AnirudhPanda** [comment]
There is some rebase issue i guess!

**Comment by PrafulAnand** [comment]
github isnt showing anything to me , the PR needs to be raised against v1.1?

**Comment by AnirudhPanda** [comment]
Nope to Main

**Comment by PrafulAnand** [comment]
let me close this then and open it to main

**Pull request closed without merging**
