### PR TITLE
Add a quote from The Hate U Give

### PR DESCRIPTION
**Pull request by Muzammil-khan710**
added a quote from the book The Hate U Give
source : https://www.bookbub.com/blog/famous-book-quotes

### CODE REVIEW

**Comment by AnirudhPanda** [comment]
Resolve merge conflicts

**Comment by Muzammil-khan710** [comment]
Resolved merge conflicts

**Comment by AnirudhPanda** [comment]
Resolve merge conflicts @Muzammil-khan710

**Comment by Muzammil-khan710** [comment]
I have resolved conflicts please check @AnirudhPanda

**Pull request merged**
